# This does not make use of any caching as to ensure a clean build
name: Publish on GitHub

on:
  release:
     types:
       - published

env:                                              
  MINECRAFT_VERSION: 1.20.6 
  JAVA_VERSION: 21
  VERSION: 0.2.2+1.20.6
  RELEASE_NAME: Skinpls 0.2.2 for Minecraft 1.20.6
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}  

permissions:
  contents: write

jobs:                                             
  build:                                          
    runs-on: ubuntu-latest                        
    steps:                                        
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build
        
      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on GitHub.
          github-token: ${{ secrets.GITHUB_TOKEN }}
